In [3]:
print("PIAIC Assignment # 1")

PIAIC Assignment # 1


In [1]:
print("Roll#PIAIC125090")

Roll#PIAIC125090


In [2]:
print("Malik Hammad Ahmed")

Malik Hammad Ahmed


In [3]:
import numpy as np

In [5]:
a = np.array([2,3,4])

In [7]:
a

array([2, 3, 4])

In [8]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
a.reshape(3,-1)


array([[2],
       [3],
       [4]])

In [14]:
a = np.arange(15)

In [15]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
a = np.random.seed(100)

In [24]:
a

In [26]:
arr = np.random.randint(1,11,size=(6, 10))

In [27]:
arr

array([[ 4,  7,  4,  5,  8,  7,  4, 10,  1,  5],
       [ 5,  6,  8,  7,  7,  3,  5,  3,  8,  2],
       [ 7,  7,  1,  8,  3,  4,  6,  5,  3,  5],
       [ 4,  8, 10,  1,  1,  6, 10,  7,  7,  6],
       [ 7,  5,  8,  4, 10,  3,  4,  9,  8,  2],
       [ 6, 10,  4,  1,  7,  3,  4,  5,  9, 10]])